// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported by this template. Run `flutterfire configure` to generate valid options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'MacOS is not supported by this template. Run `flutterfire configure` to generate valid options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported by this template. Run `flutterfire configure` to generate valid options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported by this template. Run `flutterfire configure` to generate valid options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPfWjZ5ES8OD6aPj_VqbhNgtMn-zMPGw',
    appId: '1:175856891308:android:f9567d74c7b7f00aed3609',
    messagingSenderId: '175856891308',
    projectId: 'capsule-closet-480801',
    storageBucket: 'capsule-closet-480801.firebasestorage.app',
  );

  // TODO: Run `flutterfire configure` to replace these values with your actual project configuration.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMh9gOaCDydoebJ7UD6qP1n6Q-yiXUdn0',
    appId: '1:175856891308:ios:8825aa717eab589ded3609',
    messagingSenderId: '175856891308',
    projectId: 'capsule-closet-480801',
    storageBucket: 'capsule-closet-480801.firebasestorage.app',
    iosBundleId: 'com.example.capsuleClosetApp',
  );

}